# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: false

#r:
#  - release

#branches:
#  only:
#    - master

before_install:
  - Rscript -e "if (!require('covr')) install.packages('covr')"
  - Rscript -e "if (!require('roxygen2')) install.packages('roxygen2')"
  - Rscript -e "if (!require('pkgdown')) devtools::install_github('hadley/pkgdown')"

script:
  - Rscript -e 'devtools::test()'

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'devtools::document()'
  - Rscript -e 'pkgdown::build_site()'

notifications:
  slack:
    on_success: change
