# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
#sudo: false
cache: packages

sudo: required

services:
  - docker

before_install:
  - docker pull r-base

#r:
#  - release

branches:
  only:
    - master

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  slack:
    on_success: change
