# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: false

#r:
#  - release

branches:
  only:
    - master

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'devtools::document()'
  - Rscript -e 'pkgdown::build_site()'

notifications:
  slack:
    on_success: change
