language: r
cache: packages
warnings_are_errors: false

r:
  - oldrel
  - release
  - devel

services:
  - docker

env:
  global:
    - _R_CHECK_TESTS_NLINES_=0

r_packages:
  - covr
  - lintr
  - roxygen2
  - pkgdown
  - lintr

before_install:
  - R CMD build .
  # get the app data
  - git clone https://gitlab-ci-token:$GL_TOKEN@gitlab.com/$GL_ORG
  - docker build -t hnskde/tmongr .
  - rm tmongr_*.tar.gz
  - docker run -d -p 127.0.0.1:3838:3838 --name tmongr hnskde/tmongr

before_script:
  - docker ps | grep -q tmongr
  - curl -IsSf 127.0.0.1:3838 > /dev/null
  
after_success:
  - R CMD INSTALL $PKG_TARBALL
  - |
    if [[ "$TRAVIS_R_VERSION_STRING" == "release" ]] && [[ "$TRAVIS_EVENT_TYPE" == "push" ]]; then
      Rscript -e 'covr::codecov()'
      Rscript -e 'covr::coveralls()'
      Rscript -e 'lintr::lint_package()'
    fi
  - rm -rf qmongr.Rcheck
  - Rscript -e 'roxygen2::roxygenise()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  - provider: pages
    skip_cleanup: true
    token: $GH_TOKEN
    keep_history: false
    local_dir: docs
    on:
      branch: master
      condition: $TRAVIS_R_VERSION_STRING == "release"
  # our image to dockerhub
  - provider: script
    script: bash docker_push
    skip_cleanup: true
    on:
      branch: master
      condition: $TRAVIS_R_VERSION_STRING == "release"

notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always 
