language: r
cache: packages
warnings_are_errors: false

r:
  - oldrel
  - release
  - devel

env:
  global:
    - _R_CHECK_TESTS_NLINES_=0

r_packages:
  - covr
  - lintr
  - roxygen2
  - pkgdown
  - lintr

after_success:
  - |
  if [[ "$TRAVIS_R_VERSION_STRING" == "release" ]] && [[ "$TRAVIS_EVENT_TYPE" == "push" ]]; then
    Rscript -e 'lintr::lint_package()'
    Rscript -e 'covr::codecov()'
  fi
  - Rscript -e 'roxygen2::roxygenise()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  token: $GH_TOKEN
  keep_history: false
  local_dir: docs
  on:
    branch: master
    condition: $TRAVIS_R_VERSION_STRING == "release"

notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always 

